image: debian/stable
arch: amd64
packages:
 - golang
secrets:
 - 8f9eb1fd-3d1d-4079-aff0-7bd9dcc6584b
sources:
 - git@git.sr.ht:~jeffh/cfs
tasks:
 - build: |
    cd cfs
    make
 - test: |
    cd cfs
    make test
 - race: |
    cd cfs
    make test_race
