name: Go
on: [push]
jobs:

  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest, macOS-latest]
    steps:

    - name: Set up Go 1.17.8
      uses: actions/setup-go@v1
      with:
        go-version: 1.17.8
      id: go

    - name: Granting private modules access
      run: |
        git config --global url."https://${{ secrets.GO_MODULES_TOKEN }}:x-oauth-basic@github.com/jeffh".insteadOf "https://github.com/jeffh"

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: make all
      env:
        GOARGS: -v

    - name: Test
      run: make test

    - name: Race
      run: make all test
      env:
        GOARGS: -race

