name: Go
on: [push]
jobs:

  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]
    steps:

    - name: Set up Go 1.23
      uses: actions/setup-go@v5
      with:
        go-version: 1.23
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Build
      run: make all
      env:
        GOARGS: -v

    - name: Test
      run: make test

    - name: Race
      run: make all test
      env:
        GOARGS: -race

